### ISSUE TITLE
How to fix module not found

### ISSUE THREAD

**Issue by muhfaris** [NateRadebaugh/react-datetime#1190]
### I'm Submitting a ...

```
[x] Bug report
[ ] Feature request
[ ] Support request
```

### Steps to Reproduce

1. Install `npm install --save @nateradebaugh/react-datetime`
![image](https://user-images.githubusercontent.com/16787866/86420872-1fd72880-bd02-11ea-89fe-b4a1c8fa8b9b.png)
2. Add to code 
```
import DateTime from "@nateradebaugh/react-datetime";
import "@nateradebaugh/react-datetime/scss/styles.scss";
```

### Actual Results

![image](https://user-images.githubusercontent.com/16787866/86421111-fe2a7100-bd02-11ea-9490-94ee2bfa5b62.png)

### Minimal Reproduction of the Problem

```
import DateTime from "@nateradebaugh/react-datetime";
import "@nateradebaugh/react-datetime/scss/styles.scss";

<FormGroup row>
          <Col xs="12" md="12">
            <DateTime
              inputProps={{ name: "start_date" }}
              isValidDate={validDate}
              value={this.props.data.start_date}
              onChange={this.props.onHandleChangeDate}
            />
          </Col>
        </FormGroup>


```

**Comment by NateRadebaugh** [comment]
Sorry I think this issue only exists in the latest version. Does downgrading to the previous release fix the issue for you? The issue has to do with the new semantic release github action I'm trying but it seems to be misconfigured still

**Comment by muhfaris** [comment]
nope, still error @NateRadebaugh 
I tried to version `4.3.4`
```
import DateTime from "@nateradebaugh/react-datetime@4.3.4";
```
and installed library :
```

+ @nateradebaugh/react-datetime@4.3.4
removed 41 packages, updated 1 package and audited 2030 packages in 35.398s

```
![image](https://user-images.githubusercontent.com/16787866/86480994-51d7a180-bd79-11ea-9bc0-5fd77d0ce82e.png)

**Comment by NateRadebaugh** [comment]
I was able to get `4.3.4` working just fine:
* https://codesandbox.io/s/dreamy-margulis-kvcmn

I've since deployed a new release `4.4.2` that should work now:
* https://codesandbox.io/s/lucid-christian-s5dd8
