### ISSUE TITLE
onChange callback is not triggered when value is provided

### ISSUE THREAD

**Issue by aziolek** [NateRadebaugh/react-datetime#122]
### I'm Submitting a ...

```
[x] Bug report
[ ] Feature request
[ ] Support request
```

### Steps to Reproduce
1. Create minimal React application using @nateradebaugh/react-datetime.
2. Add `onChange` API element, setting `value` to component state.
3. Add `value` API element as `this.state.value`.
4. Open DateTime, set any date, close it.
5. Open it again, try to change date.

### Expected Results
1. `onChange` callback is properly triggered with new value.

### Actual Results
1. `onChange` callback is not triggered.

### Minimal Reproduction of the Problem
Sandbox is available here: https://codesandbox.io/s/ov2rjx7z85

Minimal reproduction:
```
import React, { Component } from "react";
import { render } from "react-dom";
import DateTime from "@nateradebaugh/react-datetime";
import "@nateradebaugh/react-datetime/css/react-datetime.css";
import parse from "date-fns/parse";

class Index extends Component {
  state = {
    value: ""
  };

  changeValue = value => {
    this.setState({
      value
    });
  };

  render() {
    const { value } = this.state;
    return (
      <DateTime value={value} onChange={value => this.changeValue(value)} />
    );
  }
}

render(<Index />, document.querySelector("#root"));
```

### Other Information (e.g. stacktraces, related issues, suggestions how to fix)
* After doing some debugging with older versions of this package I've found that above reproduction triggers `onClick` callback with new value for `3.1.0`, but does not for `3.2.0`. On both versions actual `value` showed is not changing.
* When using `defaultValue` prop instead of `value` DateTime works as expected.

If it's intentional change from https://github.com/YouCanBookMe/react-datetime behaviour I think this should be described in documentation, as YouCanBookMe/react-datetime do not have that glitch and triggers `onChange` callback properly when provided with `value` prop.

**Comment by NateRadebaugh** [comment]
Thanks for the bug and repro @aziolek 

Please feel free to send out a PR to fix this if you have time.

**Comment by NateRadebaugh** [comment]
It seems if I bump the react dep in that codesandbox to use the latest version, I get an error.

I think there's some infinite loop being hit in the callback to onChange where it should not be. I can hit the issue locally but am not sure what the right way to trigger onChange is.

Current logic:
```jsx

  componentDidUpdate(prevProps: DateTimeProps, prevState: DateTimeState) {
    const prevVal = prevState.selectedDate || prevState.inputValue;
    const val = this.state.selectedDate || this.state.inputValue;
    if (
      (prevVal instanceof Date &&
        val instanceof Date &&
        !isEqual(prevVal, val)) ||
      prevVal !== val
    ) {
      this.props.onChange!(val);
    }
  }
```

**Comment by NateRadebaugh** [comment]
Hey @aziolek I published a new update to the package.

* `@nateradebaugh/react-datetime@3.3.5`

Here's your sandbox with the latest version of react and the `@nateradebaugh/react-datetime` component: https://codesandbox.io/s/j21vx0pzvv
