### ISSUE TITLE
disableCloseOnClickOutside doesn't work

### ISSUE THREAD

**Issue by aziolek** [NateRadebaugh/react-datetime#135]
### I'm Submitting a ...

```
[x] Bug report
[ ] Feature request
[ ] Support request
```

### Steps to Reproduce
1. Create minimal React application using @nateradebaugh/react-datetime.
2. Add `disableCloseOnClickOutside` prop with `true` value.
4. Open DateTime, click outside of it.

### Expected Results
1. `DateTime` is not closing.

### Actual Results
1. `DateTime` is closing.

### Minimal Reproduction of the Problem
Sandbox is available here: https://codesandbox.io/s/927lr99pp

Minimal reproduction:
```
import React, { Component } from "react";
import { render } from "react-dom";
import DateTime from "@nateradebaugh/react-datetime";
import "@nateradebaugh/react-datetime/css/react-datetime.css";

class Index extends Component {
  render() {
    return <DateTime disableCloseOnClickOutside />;
  }
}

render(<Index />, document.querySelector("#root"));
```

### Other Information (e.g. stacktraces, related issues, suggestions how to fix)
* Reproduction uses 3.3.5 version. Using 3.3.6. version in sandbox causes cross-origin React error.

**Comment by NateRadebaugh** [comment]
Thanks for filing this bug with an easy repro.

So many attributes! This should be easy to fix. I'll hope to find time this week to address unless you get to it first.

**Comment by aziolek** [comment]
I will try to find time to fix this and create PR.
I'm sorry for posting second bug report without contributing to your package myself. I will try to find some time to do so, as your datepicker is awesome -- kudos for getting rid of `moment.js`.

**Comment by NateRadebaugh** [comment]
Cool.

`index.tsx` already has the following code:
```js
  handleClickOutside() {
    if (
      this.props.input &&
      this.state.open &&
      !this.props.open &&
      !this.props.disableOnClickOutside
    ) {
      this.setState({ open: false }, () => {
        this.props.onBlur!(this.state.selectedDate || this.state.inputValue);
      });
    }
  }
```

**Comment by NateRadebaugh** [comment]
Hey @aziolek, the documented prop is `disableOnClickOutside`, which is why your `disableCloseOnClickOutside` isn't working.

See the docs at the end of https://github.com/NateRadebaugh/react-datetime/#api
