### ISSUE TITLE
Input value is not set with 4.0.0-rc.27

### ISSUE THREAD

**Issue by OscarBarrett** [NateRadebaugh/react-datetime#334]
### I'm Submitting a ...

- [x] Bug report
- [ ] Feature request
- [ ] Support request

### Steps to Reproduce

Render a DateTime component and try to select a date.

### Expected Results

The input value should be set.

### Actual Results

No value is set on the input. Tried on Chrome and Firebox.

### Minimal Reproduction of the Problem

https://codesandbox.io/s/dazzling-chatterjee-9limk

**Comment by NateRadebaugh** [comment]
Thanks for this @oscarbarrett I'll try to investigate this in the next few days.

**Comment by NateRadebaugh** [comment]
@OscarBarrett  this fork has dropped support for use uncontrolled. Instead, you must provide the "value" and "onChange" handlers for the component to work.
